feat: move cargo-generate TOML to get right repo generated, add pre-commit hooks, minor fixes in the template

diff --git a/template/justfile b/template/justfile
--- a/template/justfile
+++ b/template/justfile
@@ -8,26 +8,26 @@ help:
     @just list
 
 fmt *FLAGS:
-    cargo +nightly fmt {{FLAGS}}
+    cargo +nightly fmt {% raw  %}{{FLAGS}}{% endraw %}
 
 test *FLAGS:
-    cargo nextest run {{FLAGS}}
+    cargo nextest run {% raw  %}{{FLAGS}}{% endraw %}
 
-{% if crate_type == "bin" %}watch *FLAGS:
-    echo # things required by `just watch`
-    cargo install cargo-watch{% endif %}
-
+{% if crate_type == "bin" %}run *FLAGS:
+    cargo run {% raw  %}{{FLAGS}}{% endraw %}
+{% endif %}
 pre-commit:
     @just fmt
     cargo spellcheck fix
     cargo clippy
+    cargo clippy --tests
     @just test
 
-coverage:
-    cargo llvm-cov --open
+coverage *FLAGS:
+    cargo llvm-cov {% raw %}{{FLAGS}}{% endraw %} --open
 
-benchmark:
-    cargo criterion
+benchmark *FLAGS:
+    cargo criterion {% raw %}{{FLAGS}}{% endraw %}
 
 thorough-check:
     cargo +nightly udeps
@@ -44,22 +44,25 @@ unused-features:
 
 init:
     echo # installing git hooks
-    pip install pre-commit
-    pre-commit install
+    pre-commit --version || pip install pre-commit
+    pre-commit install || echo "failed to install git hooks!" 1>&2
     echo # installing nightly used by `just fmt` and `cargo udeps`
     rustup install nightly
+    echo # installing cargo-binstall for faster setup time
+    cargo install cargo-binstall
     echo # things required by `just test`
-    cargo install cargo-nextest
+    cargo binstall cargo-nextest --no-confirm
     {% if crate_type == "bin" %}echo # things required by `just watch`
-    cargo install cargo-watch{% endif %}
+    cargo binstall cargo-watch --no-confirm{% endif %}
     echo # things required by `just pre-commit`
-    cargo install cargo-spellcheck --locked
-    cargo spellcheck completions # shell auto-completions for cargo-spellcheck
+    cargo binstall cargo-spellcheck --no-confirm
+    echo # things required by `just coverage`
+    rustup component add llvm-tools-preview
+    cargo binstall cargo-llvm-cov --no-confirm
+    echo # things required by `just benchmark`
+    cargo binstall cargo-criterion --no-confirm
     echo # things required by `just thorough-check`
-    rustup component add llvm-tools-preview # required by cargo-llvm-cov
-    cargo install \
-      cargo-udeps --locked \
-      cargo-llvm-cov \
-      cargo-audit \
-      cargo-criterion \
-      cargo-upgrades
+    cargo binstall cargo-udeps --no-confirm
+    cargo binstall cargo-audit --no-confirm
+    cargo binstall cargo-upgrades --no-confirm
+    cargo binstall cargo-unused-features --no-confirm
